image: node:14

stages:
  - build
  - release

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - packages/*/node_modules/
    - dist/
    - .npm
    - .cache/

before_script:
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

build:
  stage: build
  tags: 
    - alerta-webui
  script:
    - npm install --cache .npm
    #- npm ci --cache .npm --prefer-offline --no-audit  
    - export BASE_URL="/alerta/"
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
  rules:
    - if: '$CI_COMMIT_BRANCH != "master"'
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always 

release:
  stage: release
  tags: 
    - alerta-webui
  script:
    - scp -r dist/* root@10.6.128.107:/var/www/alerta-ui-subpath/
  dependencies:
    - build
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: on_success