name: Deploy

on:
  push:
    branches: [ master, release/* ]
  pull_request:
    branches: [ master, release/* ]

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '14'
      - run: npm version
      - run: npm install
      - name: Lint
        id: lint
        run: npm run lint:nofix
      - name: Unit Test
        id: unit-test
        run: npm run test:unit
      - uses: act10ns/slack@v2
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: failure()

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '14'
      - run: npm version
      - run: npm install
      - run: |
          echo BASE_URL=./ > .env
          echo VUE_APP_ALERTA_ENDPOINT=https://alerta-api.fly.dev >> .env
          echo VUE_APP_TRACKING_ID=UA-44644195-1 >> .env
      - name: Build
        id: build
        run: npm run build
      - name: Deploy
        id: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
      - uses: act10ns/slack@v2
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
