name: Tests

on:
  push:
  pull_request:
    branches: [ master ]

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '14'
    - run: npm version
    - id: build
      run: npm install
    - id: format-check
      run: npm run format-check
    - id: lint
      run: npm run lint:nofix
    - uses: act10ns/slack@v2
      with:
        status: ${{ job.status }}
      if: failure()

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '14'
    - run: npm version
    - run: npm install
    - id: unit-test
      run: npm run test:unit
    # - id: e2e-test
    #   run: npm run test:e2e
    - uses: act10ns/slack@v2
      with:
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
      if: failure()

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '14'
    - run: npm version
    - id: build
      run: |
        npm install
        npm run all
    - uses: act10ns/slack@v2
      with:
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
      if: always()
